### ISSUE TITLE
微软的 API 地址，从 eastus.tts.speech.microsoft.com 迁到了 eastus.api.speech.microsoft.com，语音列表无法显示，请修正。

### ISSUE THREAD

**Issue by lighterhy** [skygongque/tts#10]
微软的 API 地址，从 eastus.tts.speech.microsoft.com 迁到了 eastus.api.speech.microsoft.com，语音列表无法显示，请修正。

**Comment by leeooo001** [comment]
嗯，好像已经不能用了。。。

**Comment by skygongque** [comment]
> 微软的 API 地址，从 eastus.tts.speech.microsoft.com 迁到了 eastus.api.speech.microsoft.com，语音列表无法显示，请修正。

油猴脚本已经修复，python命令行版本有空再修

**Comment by skygongque** [comment]
python命令行版本也已经修复完毕,但`wss://eastus.api.speech.microsoft.com/cognitiveservices/websocket/v1` 接口目前几乎没有认证可能很快失效

**Comment by lighterhy** [comment]
非常感谢你的辛勤工作。

**Comment by snowman** [comment]
非常感谢你的辛勤工作。

**Comment by lighterhy** [comment]
> > 微软的 API 地址，从 eastus.tts.speech.microsoft.com 迁到了 eastus.api.speech.microsoft.com，语音列表无法显示，请修正。
> 
> 油猴脚本已经修复，python命令行版本有空再修

测试了一下，切换语言以后播放按钮不可用。问题没有解决。

**Comment by tattataattt2** [comment]
用不了了 啥情况
```
Traceback (most recent call last):
  File "D:\cl\tts\python_cli_demo\tts.py", line 105, in <module>
    asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
  File "D:\xx_zd\python3_11_2\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\cl\tts\python_cli_demo\tts.py", line 95, in mainSeq
    await transferMsTTSData(SSML_text, outputPath)
  File "D:\cl\tts\python_cli_demo\tts.py", line 47, in transferMsTTSData
    Auth_Token = re.findall(token_expr, main_web_content)[0]
IndexError: list index out of rang
```

**Comment by skygongque** [comment]
> 用不了了 啥情况
> 
> ```
> Traceback (most recent call last):
>   File "D:\cl\tts\python_cli_demo\tts.py", line 105, in <module>
>     asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
>   File "D:\xx_zd\python3_11_2\lib\asyncio\base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "D:\cl\tts\python_cli_demo\tts.py", line 95, in mainSeq
>     await transferMsTTSData(SSML_text, outputPath)
>   File "D:\cl\tts\python_cli_demo\tts.py", line 47, in transferMsTTSData
>     Auth_Token = re.findall(token_expr, main_web_content)[0]
> IndexError: list index out of rang
> ```

请用最新版，你这个报错行我都注释掉了

**Comment by tattataattt2** [comment]
> > 用不了了 啥情况
> > ```
> > Traceback (most recent call last):
> >   File "D:\cl\tts\python_cli_demo\tts.py", line 105, in <module>
> >     asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
> >   File "D:\xx_zd\python3_11_2\lib\asyncio\base_events.py", line 642, in run_until_complete
> >     return future.result()
> >   File "D:\cl\tts\python_cli_demo\tts.py", line 95, in mainSeq
> >     await transferMsTTSData(SSML_text, outputPath)
> >   File "D:\cl\tts\python_cli_demo\tts.py", line 47, in transferMsTTSData
> >     Auth_Token = re.findall(token_expr, main_web_content)[0]
> > IndexError: list index out of rang
> > ```
> 
> 请用最新版，你这个报错行我都注释掉了

好的感谢 解决了!!!

**Comment by jsenser** [comment]
9月23 不能用了

**Comment by cancundeyingzi** [comment]
> 9月23 不能用了

我刚刚还能用

**Comment by cancundeyingzi** [comment]
一早起来也寄了,昨天还可以的,是我网络问题?
```
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
    transport, protocol = await self._create_connection()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1016, in create_connection
    infos = await self._ensure_resolved(
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1395, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 855, in getaddrinfo
    return await self.run_in_executor(
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\py\tts转录到麦克风\main.py", line 137, in 微软输入
    asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\py\tts转录到麦克风\main.py", line 78, in mainSeq
    await transferMsTTSData(SSML_text, outputPath)
  File "D:\py\tts转录到麦克风\main.py", line 41, in transferMsTTSData
    async with websockets.connect(endpoint2) as websocket:
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 633, in __aenter__
    return await self
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by lilbeauty** [comment]
不能用了，这个api 会被reject ，博主有办法看下什么原因吗？
