### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by RouderSky** [skygongque/tts#13]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\legacy\protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\legacy\protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\legacy\protocol.py", line 1088, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\legacy\protocol.py", line 1147, in read_frame
    extensions=self.extensions,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\legacy\framing.py", line 70, in read
    data = await reader(2)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tts.py", line 109, in <module>
    asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "tts.py", line 99, in mainSeq
    await transferMsTTSData(SSML_text, outputPath)
  File "tts.py", line 78, in transferMsTTSData
    response = await websocket.recv()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\legacy\protocol.py", line 552, in recv
    await self.ensure_open()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\legacy\protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent

**Comment by RouderSky** [comment]
音频超过一分钟就报这个错了

**Comment by skygongque** [comment]
接口已换原接口问题参考价值不大
