### ISSUE TITLE
Too Many Requests 问题：429

### ISSUE THREAD

**Issue by leonuxzy** [skygongque/tts#14]
今天转化完，看了下才成功了一半，显示服务器拒绝连接。
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429
不知道是不是有什么限制，求大神帮忙看下怎么处理，感激不尽~！

具体报错如下：
Traceback (most recent call last):
  File "C:\*\tts\python_cli_demo - sfb\tts.py", line 108, in <module>
    asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\*\tts\python_cli_demo - sfb\tts.py", line 98, in mainSeq
    await transferMsTTSData(SSML_text, outputPath)
  File "C:\*\tts\python_cli_demo - sfb\tts.py", line 57, in transferMsTTSData
    async with websockets.connect(endpoint2) as websocket:
  File "C:\Users\*\AppData\Roaming\Python\Python39\site-packages\websockets\legacy\client.py", line 633, in __aenter__
    return await self
  File "C:\Users\*\AppData\Roaming\Python\Python39\site-packages\websockets\legacy\client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
  File "C:\Users\*\AppData\Roaming\Python\Python39\site-packages\websockets\legacy\client.py", line 658, in __await_impl__
    await protocol.handshake(
  File "C:\Users\*\AppData\Roaming\Python\Python39\site-packages\websockets\legacy\client.py", line 328, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429

**Comment by skygongque** [comment]
应该是IP被限制
