### ISSUE TITLE
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429

### ISSUE THREAD

**Issue by mn860429** [skygongque/tts#17]
035BE9F910F44BFC98F1115F40F3F881
Traceback (most recent call last):
  File "tts.py", line 108, in <module>
    asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
  File "C:\Users\2019\Anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "tts.py", line 98, in mainSeq
    await transferMsTTSData(SSML_text, outputPath)
  File "tts.py", line 57, in transferMsTTSData
    async with websockets.connect(endpoint2,extra_headers={'Origin':'https://azure.microsoft.com'}) as websocket:
  File "C:\Users\2019\Anaconda3\lib\site-packages\websockets\legacy\client.py", line 633, in __aenter__
    return await self
  File "C:\Users\2019\Anaconda3\lib\site-packages\websockets\legacy\client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\Users\2019\Anaconda3\lib\asyncio\tasks.py", line 416, in wait_for
    return fut.result()
  File "C:\Users\2019\Anaconda3\lib\site-packages\websockets\legacy\client.py", line 663, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "C:\Users\2019\Anaconda3\lib\site-packages\websockets\legacy\client.py", line 328, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429

**Comment by TommyRoy776** [comment]
我也遇到了 有沒有大佬找到rate limit? 
我用了一整天才429 我是用for loop跑了大概30個800字txt文件才報錯

**Comment by EECSMiner** [comment]
<img width="234" alt="image" src="https://user-images.githubusercontent.com/25608683/221768889-cc9c270c-6bb6-4e8c-8b54-6eb481f7445e.png">
<img width="131" alt="image" src="https://user-images.githubusercontent.com/25608683/221769990-c38fa3f8-d8f9-4e3a-bf00-0017af2a3e7c.png">

最大访问次数50次，重置周期差不多24h
