### ISSUE TITLE
C:\Users\dengz\Downloads\tts\tts.py:108: DeprecationWarning: There is no current event loop

### ISSUE THREAD

**Issue by bk111** [skygongque/tts#22]
I got the warning:

python tts.py --input SSML.xml
C:\Users\dengz\Downloads\tts\tts.py:108: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
F9932303087047B88653BDAE462F4591
Traceback (most recent call last):
  File "C:\Users\dengz\Downloads\tts\tts.py", line 108, in <module>
    asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
  File "C:\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\dengz\Downloads\tts\tts.py", line 98, in mainSeq
    await transferMsTTSData(SSML_text, outputPath)
  File "C:\Users\dengz\Downloads\tts\tts.py", line 57, in transferMsTTSData
    async with websockets.connect(endpoint2,extra_headers={'Origin':'https://azure.microsoft.com'}) as websocket:
  File "C:\Python310\lib\site-packages\websockets\legacy\client.py", line 642, in __aenter__
    return await self
  File "C:\Python310\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Python310\lib\site-packages\websockets\legacy\client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "C:\Python310\lib\site-packages\websockets\legacy\client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429

**Comment by skygongque** [comment]
429 ip被限制
