### ISSUE TITLE
不支持情感 

### ISSUE THREAD

**Issue by 0000duck** [skygongque/tts#27]
SSML.xml
<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
<voice  name="zh-CN-YunyangNeural">
    <mstts:express-as style="poetry-reading">
        <prosody  rate="0%" pitch="0%">
		晓晓的声音
		</prosody>
    </mstts:express-as>
</voice>
</speak>

报错
tts.py:119: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
04CF12008D864E2CA1CD4B785066F6D4
receiving...
Traceback (most recent call last):
  File "V:\tts-main\python_cli_demo\tts.py", line 119, in <module>
    asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
  File "C:\Users\888\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "V:\tts-main\python_cli_demo\tts.py", line 109, in mainSeq
    await transferMsTTSData(SSML_text, outputPath)
  File "V:\tts-main\python_cli_demo\tts.py", line 88, in transferMsTTSData
    response = await websocket.recv()
  File "C:\Users\888\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 552, in recv
    await self.ensure_open()
  File "C:\Users\888\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1007 (invalid data) SSML is invalid; then sent 1007 (invalid data) SSML is invalid

**Comment by skygongque** [comment]
更换了api
目前使用的api确实不支持情感
```
WSS_URL = (
        "wss://speech.platform.bing.com/consumer/speech/synthesize/"
        + "readaloud/edge/v1?TrustedClientToken="
        + TRUSTED_CLIENT_TOKEN
    )
```

**Comment by skygongque** [comment]
https://github.com/skygongque/tts#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E
本仓库更新过接口之前是azure接口的试用，现在是edge接口，有些声音不支持
刚才添加了microsoft接口，支持部分说话风格，但该接口并不稳定
