### ISSUE TITLE
python程序报错

### ISSUE THREAD

**Issue by cancundeyingzi** [skygongque/tts#9]
```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\py\爬虫\tts.py", line 105, in <module>
    asyncio.get_event_loop().run_until_complete(mainSeq(SSML_text, output_path))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\py\爬虫\tts.py", line 95, in mainSeq
    await transferMsTTSData(SSML_text, outputPath)
  File "D:\py\爬虫\tts.py", line 43, in transferMsTTSData
    r = requests.get(endpoint1)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='azure.microsoft.com', port=443): Max retries exceeded with url: /en-gb/services/cognitive-services/text-to-speech/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
```

**Comment by snowman** [comment]
挂代理

**Comment by cancundeyingzi** [comment]
> 挂代理

非最优解

**Comment by skygongque** [comment]
目前版本应该不会遇到这个问题，因为`requests`根本没调用
